name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        EC2_USER: ec2-user
        EC2_HOST: ec2-54-211-148-120.compute-1.amazonaws.com
        EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        REPO_NAME: justmobile-node
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          cd proxy/justmobile-node
          git pull origin main
          npm install
          # pm2 restart all
        EOF